const express = require('express');
const { query, isPostgres } = require('../db');
const router = express.Router();

async function ensureDownloadsTable() {
  if (isPostgres()) {
    await query(
      'CREATE TABLE IF NOT EXISTS downloads (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lesson_id INTEGER, filename TEXT NOT NULL, url TEXT NOT NULL, description TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)'
    );
    return;
  }
  try {
    await query(
      'CREATE TABLE IF NOT EXISTS downloads (id INTEGER PRIMARY KEY AUTOINCREMENT, lesson_id INTEGER, filename TEXT NOT NULL, url TEXT NOT NULL, description TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)'
    );
    return;
  } catch (err) {
    // MySQL fallback below
  }
  await query(
    'CREATE TABLE IF NOT EXISTS downloads (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, lesson_id INT UNSIGNED, filename VARCHAR(255) NOT NULL, url VARCHAR(1000) NOT NULL, description TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)'
  );
}

// List all downloads
router.get('/', async (req, res, next) => {
  try {
    await ensureDownloadsTable();
    const rows = await query('SELECT id, lesson_id, filename, url, description FROM downloads ORDER BY id DESC');
    res.json(rows || []);
  } catch (err) {
    next(err);
  }
});

// List downloads for a lesson
router.get('/lesson/:lessonId', async (req, res, next) => {
  try {
    await ensureDownloadsTable();
    const lessonId = req.params.lessonId;
    const rows = await query('SELECT id, filename, url, description FROM downloads WHERE lesson_id = ? ORDER BY id DESC', [lessonId]);
    res.json(rows || []);
  } catch (err) {
    next(err);
  }
});

module.exports = router;
